remove switching to signed images
let's see if we still need this, currently this is the reason why the
installation is failing with:

```
error: Switching: No such file or directory (os error 2)
```